# docker-compose.yml - Only for local debug purposes
# docker-compose up -d elasticsearch kibana jaeger camunda redis mongo mysql postgres pgadmin
version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: local-postgres
    environment:
      TZ: UTC
      POSTGRES_DB: postgres_database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
      # get ip address for connect to pgadmin
      # docker inspect loc-postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: local-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"